local:
  config:
    auth:
      server:
        host: 192.168.89.1
        port: 9000
        path: auth-server
      client:
        host: 192.168.89.1
        port: 8080
        path: auth-client
      resource:
        host: 192.168.89.1
        port: 8090
        path: resource-server

logging:
  level:
    root: DEBUG