local:
  config:
    localhost: 192.168.217.1
    auth:
      server:
        host: ${local.config.localhost}
        port: 9000
        path: auth-server
      client:
        host: ${local.config.localhost}
        port: 8080
        path: auth-client
      resource:
        host: ${local.config.localhost}
        port: 8090
        path: resource-server

logging:
  level:
    root: DEBUG