logging:
  level:
    root: INFO

messages:
  base-uri: http://${local.config.auth.resource.host}:${local.config.auth.resource.port}/${local.config.auth.resource.path}/messages

oauth2:
  authorization:
    uri: http://${local.config.auth.server.host}:${local.config.auth.server.port}/${local.config.auth.server.path}/oauth2/authorize
  token:
    uri: http://${local.config.auth.server.host}:${local.config.auth.server.port}/${local.config.auth.server.path}/oauth2/token

server:
  port: 8080
  servlet:
    context-path: /auth-client

spring:
  application:
    name: "auth-client"
  profiles:
    active: dev
  thymeleaf:
    encoding: UTF-8
    cache: false
    check-template: true
    check-template-location: true

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
  env:
    active: ${spring.profiles.active}

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: [health,info]