jwk:
  set:
    uri: http://${local.config.auth.server.host}:${local.config.auth.server.port}/${local.config.auth.server.path}/oauth2/jwks

logging:
  level:
    root: INFO

server:
  port: ${local.config.auth.resource.port}
  servlet:
    context-path: /${local.config.auth.resource.path}

spring:
  application:
    name: "resource-server"
  profiles:
    active: dev

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
  env:
    active: ${spring.profiles.actice}

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: [health,info]